services:
  build-kria:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xilinx-yocto
    environment:
      - MACHINE=k26-smk-kv-sdt
    volumes:
      - ${COMPOSE_PROJECT_DIRECTORY}:${COMPOSE_PROJECT_DIRECTORY}
      - /opt/yocto:/opt/yocto
    working_dir: ${COMPOSE_PROJECT_DIRECTORY}
    command: /bin/bash -c "source ${COMPOSE_PROJECT_DIRECTORY}/setupsdk > /dev/null && bitbake kria-image-full-cmdline"
    tty: true
    stdin_open: true
