services:
  build-kria:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xilinx-yocto
    environment:
      - MACHINE=k26-smk-kv-sdt
    volumes:
      - .:${PWD}
      - /opt/yocto:/opt/yocto
    working_dir: ${PWD}
    command: /bin/bash -c "source ${PWD}/setupsdk > /dev/null && bitbake kria-image-full-cmdline"
    tty: true
    stdin_open: true
